foodplan/urls.py
import os

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from foodplan import settings
from foodplan_site.views import index, free_menus, card

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('free_menus/', free_menus, name='free_menus'),
    path('card/', card, name='card'),
    path('users/', include('users.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import login, registration, profile, logout, order

app_name = 'users'

urlpatterns = [
    path('auth/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('lk/', profile, name='profile'),
    path('logout/', logout, name='logout'),
    path('order/', order, name='order'),
]

templates/card1.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
    <title>План питания на неделю, меню, рецепты, список покупок. Классическое меню, безуглеводное меню</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light fixed-top navbar__opacity">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <img src="img/logo.8d8f24edbb5f.svg" height="55" width="189" alt="">
                </a>
                <button class="btn btn-outline-success me-2 shadow-none foodplan_green foodplan__border_green">Назад</button>
            </div>
        </nav>
    </header>
    <main style="margin-top: calc(2rem + 75px);">
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-4 d-flex justify-content-center">
                        <div class="card foodplan__card_borderless">
                            <img src="img/circle1.png" alt="">
                        </div>
                    </div>
                    <div class="col-12 col-md-6 d-flex flex-column justify-content-between">
                        <h2>Название рецепта</h2>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">ингредиент (500г.)</li>
                            <li class="list-group-item">ингредиент (500г.)</li>
                            <li class="list-group-item">ингредиент (500г.)</li>
                            <li class="list-group-item">ингредиент (500г.)</li>
                            <li class="list-group-item">ингредиент (500г.)</li>
                        </ul>
                        <h6>Общая калорийность: 1000 ккал</h6>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <footer>
        <nav class="navbar navbar-expand-md navbar-light mt-5">
            <div class="container p-2">
                <a class="navbar-brand" href="#">
                    <img src="img/logo.8d8f24edbb5f.svg" height="55" width="189" alt="">
                </a>
                <div class="footer__sideBtns d-flex">
                    <a href="#">
                        <img src="img/vk.png" height="38" width="auto" alt="">
                    </a>
                </div>
            </div>
        </nav>
    </footer>
    <footer class="footer pt-2" style="border-top: 1px solid lightgray;">
        <div class="container d-flex flex-row justify-content-center mb-2">
            <small class="text-center">
                <h6>© Девман2022. Все права защищены. © Devman2022. All right reserved.</h6>
                <a href="#" class="link-secondary">Политика конфиденциальности</a>
            </small>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

templates/card2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>План питания на неделю, меню, рецепты, список покупок. Классическое меню, безуглеводное меню</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light fixed-top navbar__opacity">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <img src="{% static "img/logo.8d8f24edbb5f.svg" %}" height="55" width="189" alt="">
                </a>
                {% if user_id %}
                <button class="btn btn-outline-success me-2 shadow-none foodplan_green foodplan__border_green"
                 onclick="window.location.href='{{lk}}'">Назад</button>
                {% else %}
                <button class="btn btn-outline-success me-2 shadow-none foodplan_green foodplan__border_green"
                 onclick="window.location.href='{% url 'free_menus' %}'">Назад</button>
                {% endif %}
            </div>
        </nav>
    </header>
    <main style="margin-top: calc(2rem + 75px);">
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-4 d-flex justify-content-center">
                        <div class="card foodplan__card_borderless">
                            <img src="{% if receipt.image %} {{ receipt.image.url }} {% else %} {% static 'img/circle1.png' %} {% endif %}"
                                 width="300"  alt="">
                        </div>
                    </div>
                    <div class="col-12 col-md-8 d-flex flex-column justify-content-between" style="vertical-align: top">
                        <div class="row" style="vertical-align: middle">
                            <h2>{{receipt.name}}</h2>
                            <div class="col-12 col-sm-6 d-flex flex-column justify-content-between" style="vertical-align: top">
                                <h6>Описание рецепта.</h6>
                                <h6 style="vertical-align: top">{{receipt.description}}</h6>
                            </div>
                            <div class="col-12 col-sm-6">
                                <small class="link-secondary">Ингредиенты:</small>
                                <ul class="list-group list-group-flush">
                                    {% for product in products %}
                                    <li class="list-group-item disabled"><small>{{product.product.name}} ({{product.amount}}г.)</small></li>
                                    {% endfor %}
                                <small class="link-secondary">Общая калорийность: {{receipt.calories}} ккал</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <footer>
        <nav class="navbar navbar-expand-md navbar-light mt-5">
            <div class="container p-2">
                <a class="navbar-brand" href="#">
                    <img src="{% static "img/logo.8d8f24edbb5f.svg" %}" height="55" width="189" alt="">
                </a>
                <div class="footer__sideBtns d-flex">
                    <a href="#">
                        <img src="{% static "img/vk.png" %}" height="38" width="auto" alt="">
                    </a>
                </div>
            </div>
        </nav>
    </footer>
    <footer class="footer pt-2" style="border-top: 1px solid lightgray;">
        <div class="container d-flex flex-row justify-content-center mb-2">
            <small class="text-center">
                <h6>© Девман2022. Все права защищены. © Devman2022. All right reserved.</h6>
                <a href="/media/Confidential.pdf" class="link-secondary">Политика конфиденциальности</a>
            </small>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

templates/card3.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
    <title>План питания на неделю, меню, рецепты, список покупок. Классическое меню, безуглеводное меню</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light fixed-top navbar__opacity">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <img src="img/logo.8d8f24edbb5f.svg" height="55" width="189" alt="">
                </a>
                <button class="btn btn-outline-success me-2 shadow-none foodplan_green foodplan__border_green">Назад</button>
            </div>
        </nav>
    </header>
    <main style="margin-top: calc(2rem + 75px);">
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-4 d-flex justify-content-center">
                        <div class="card foodplan__card_borderless">
                            <img src="img/circle1.png" alt="">
                        </div>
                    </div>
                    <div class="col-12 col-md-8 d-flex flex-column justify-content-between">
                        <div class="row">
                            <h2>Название рецепта</h2>
                            <div class="col-12 col-sm-6">
                                <h6>Рецепт рецепт Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi eius nemo voluptatum minus
                                    facilis blanditiis ut architecto rem maiores, aperiam aut debitis repellat quod voluptates natus, laboriosam hic
                                    adipisci non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi eius nemo voluptatum minus
                                    facilis blanditiis ut architecto rem maiores, aperiam aut debitis repellat quod voluptates natus, laboriosam hic
                                    adipisci non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi eius nemo voluptatum minus
                                    facilis blanditiis ut architecto rem maiores, aperiam aut debitis repellat quod voluptates natus, laboriosam hic
                                    adipisci non.</h6>
                            </div>
                            <div class="col-12 col-sm-6">
                                <small class="link-secondary">Ингредиенты:</small>
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                    <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                    <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                    <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                    <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                </ul>
                                <small class="link-secondary">Общая калорийность: 1000 ккал</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <footer>
        <nav class="navbar navbar-expand-md navbar-light mt-5">
            <div class="container p-2">
                <a class="navbar-brand" href="#">
                    <img src="img/logo.8d8f24edbb5f.svg" height="55" width="189" alt="">
                </a>
                <div class="footer__sideBtns d-flex">
                    <a href="#">
                        <img src="img/vk.png" height="38" width="auto" alt="">
                    </a>
                </div>
            </div>
        </nav>
    </footer>
    <footer class="footer pt-2" style="border-top: 1px solid lightgray;">
        <div class="container d-flex flex-row justify-content-center mb-2">
            <small class="text-center">
                <h6>© Девман2022. Все права защищены. © Devman2022. All right reserved.</h6>
                <a href="#" class="link-secondary">Политика конфиденциальности</a>
            </small>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

templates/footer.html
{% load static %}
    <footer class="footer py-4 mt-5" style="border-top: 1px solid lightgray;">
        <div class="container d-flex flex-row justify-content-between mb-2">
            <a href="https://vk.com/devmanorg">
                <img src="{% static "img/vk.png" %}" height="40" width="auto" alt="">
            </a>
            <div>
                <a href="{% url 'index' %}" class="link-dark mx-1" style="text-decoration: none;"><b>Главная</b></a>
                <a href="#" class="link-dark mx-1" style="text-decoration: none;"><b>Блог</b></a>
                <a href="#" class="link-dark mx-1" style="text-decoration: none;"><b>Контакты</b></a>
            </div>
        </div>
        <div class="container">
            <h6 class="link-secondary text-center"><a href="/media/Confidential.pdf" class="link-secondary me-2">Политика конфиденциальности</a><a href="/media/Confidential.pdf" class="link-secondary">Пользовательское соглашение</a></h6>
            <h6 class="link-secondary text-center">© Devman 2022. All right reserved.</h6>
        </div>
    </footer>

templates/free_menus.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
{% include "header.html" %}
<body>
    <main style="margin-top: calc(2rem + 85px);">
        <section>
            <div class="container my-5">
                <div class="row d-flex justify-content-center">
                    <div class="col-sm-6 col-lg-3">
                        <div class="card mb-1 foodplan__card_borderless">
                            <img src="{% static "img/menu11.jpg" %}" class="card-img-top" alt="">
                            <div class="card-body">
                                <h5 class="card-title" style="text-align: center"><b><a href="{% url 'card' %}?receipt_id={{receipt_chart.0}}&next={{path}}">Рецепт №1</a></b></h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-lg-3">
                        <div class="card mb-1 foodplan__card_borderless">
                            <img src="{% static "img/menu33.jpg" %}" class="card-img-top" alt="">
                            <div class="card-body">
                                <h5 class="card-title" style="text-align: center"><b><a href="{% url 'card' %}?receipt_id={{receipt_chart.1}}&next={{path}}">Рецепт №2</a> </b></h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-lg-3">
                        <div class="card mb-1 foodplan__card_borderless">
                            <img src="{% static "img/menu44.jpg" %}" class="card-img-top" alt="">
                            <div class="card-body">
                                <h5 class="card-title" style="text-align: center"><b><a href="{% url 'card' %}?receipt_id={{receipt_chart.2}}&next={{path}}">Рецепт №3</a></b></h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
         </main>
{% include "footer.html" %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/header.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>План питания на неделю, меню, рецепты, список покупок. Классическое меню, безуглеводное меню</title>
</head>
<body>
        <header>
        <nav class="navbar navbar-expand-md navbar-light fixed-top navbar__opacity">
            <div class="container">
                <a class="navbar-brand" href="{% url 'index' %}">
                    <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse1"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse1">
                    <ul class="navbar-nav w-100">
                        {% if user.is_authenticated %}

                            <li class="nav-item align-items-center d-md-flex flex-grow-1 justify-content-end">
                                <button class="btn btn-outline-success me-2 shadow-none foodplan_green foodplan__border_green"
                                onclick="window.location.href='{% url 'users:profile' %}'">Личный кабинет</button>
                                <button class="btn btn-outline-success shadow-none foodplan_green foodplan__border_green"
                                onclick="window.location.href='{% url 'users:logout' %}'">Выйти</button>
                            </li>
                        {% else %}
                            <li class="nav-item align-items-center d-md-flex flex-grow-1 justify-content-end">
                                <button class="btn btn-outline-success shadow-none foodplan_green foodplan__border_green"
                                onclick="window.location.href='{% url 'users:login' %}'">Войти</button>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>

templates/order.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
    <title>Foodplan 2021 - Меню на неделю FOODPLAN</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light fixed-top navbar__opacity">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <img src="img/logo.8d8f24edbb5f.svg" height="55" width="189" alt="">
                </a>
                <h3 class="text-secondary mt-2 me-2">Стоимость: 00000₽</h3>
                <button form="order" type="submit" class="btn shadow-none btn-sm btn-outline-success foodplan_green foodplan__border_green">Оплатить</button>
            </div>
        </nav>
    </header>
    <main style="margin-top: calc(2rem + 85px);">
        <section>
            <div class="container">
                <h1><strong class="foodplan_green">1 шаг </strong>до первого меню</h1>
                <h5 class="text-secondary mb-3">Вам будет доступно 4 типа меню: Классическое, Низкоуглеводное, Вегетарианское и Кето.</h5>
                <div class="row mb-5">
                    <div class="col-6 col-md-3">
                        
                        <label for="classic" class="position-relative" style="cursor: pointer;">
                            <img src="img/menu_classical.png" alt="" class="w-100">
                            <input form="order" type="radio" name="foodtype" id="classic" value="classic" class="foodplan_selected d-none">
                            <div class="img_selected" id="img1"></div>
                        </label>
                    </div>
                    <div class="col-6 col-md-3">
                        
                        <label for="low" class="position-relative" style="cursor: pointer;">
                            <img src="img/menu_nizkougl.png" alt="" class="w-100">
                            <input form="order" type="radio" name="foodtype" id="low" value="low" class="foodplan_selected d-none">
                            <div class="img_selected" id="img2"></div>
                        </label>
                    </div>
                    <div class="col-6 col-md-3">
                        
                        <label for="veg" class="position-relative" style="cursor: pointer;">
                            <img src="img/menu_veg.png" alt="" class="w-100">
                            <input form="order" type="radio" name="foodtype" id="veg" value="veg" class="foodplan_selected d-none">
                            <div class="img_selected" id="img3"></div>
                        </label>
                    </div>
                    <div class="col-6 col-md-3">
                        
                        <label for="keto" class="position-relative" style="cursor: pointer;">
                            <img src="img/menu_keto.png" alt="" class="w-100">
                            <input form="order" type="radio" name="foodtype" id="keto" value="keto" class="foodplan_selected d-none">
                            <div class="img_selected" id="img4"></div>
                        </label>
                    </div>
                </div>
                <h2><strong>Выберите подходящий тариф</strong></h2>
                <form id="order">
                <table class="table text-center text-truncate mb-5">
                    <tbody>
                        <tr>
                            <th scope="row" class="text-start">Срок</th>
                            <td>
                                <select class="form-select">
                                    <option value="0" selected>1 мес.</option>
                                    <option value="1">3 мес.</option>
                                    <option value="2">6 мес.</option>
                                    <option value="3">12 мес.</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row" class="text-start">Завтраки</th>
                            <td>
                                <select name="select1" class="form-select">
                                    <option value="0" selected>&#10004;</option>
                                    <option value="1">&#10008;</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row" class="text-start">Обеды</th>
                            <td>
                                <select name="select2" class="form-select">
                                    <option value="0" selected>&#10004;</option>
                                    <option value="1">&#10008;</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row" class="text-start">Ужины</th>
                            <td>
                                <select name="select3" class="form-select">
                                    <option value="0" selected>&#10004;</option>
                                    <option value="1">&#10008;</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row" class="text-start">Десерты</th>
                            <td>
                                <select name="select4" class="form-select">
                                    <option value="0" selected>&#10004;</option>
                                    <option value="1">&#10008;</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row" class="text-start">Кол-во персон</th>
                            <td>
                                <select name="select5" class="form-select">
                                    <option value="0" selected>1</option>
                                    <option value="1">2</option>
                                    <option value="2">3</option>
                                    <option value="3">4</option>
                                    <option value="4">5</option>
                                    <option value="5">6</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row" class="text-start">Аллергии</th>
                            <td>
                                <div class="form-check d-flex justify-content-start">
                                    <input class="form-check-input me-1 foodplan_checked-green" type="checkbox" value="" name="allergy1">
                                    <label class="form-check-label" for="allergy1">
                                        Рыба и морепродукты
                                    </label>
                                </div>
                                <div class="form-check d-flex justify-content-start">
                                    <input class="form-check-input me-1 foodplan_checked-green" type="checkbox" value="" name="allergy2">
                                    <label class="form-check-label" for="allergy2">
                                        Мясо
                                    </label>
                                </div>
                                <div class="form-check d-flex justify-content-start">
                                    <input class="form-check-input me-1 foodplan_checked-green" type="checkbox" value="" name="allergy3">
                                    <label class="form-check-label" for="allergy3">
                                        Зерновые
                                    </label>
                                </div>
                                <div class="form-check d-flex justify-content-start">
                                    <input class="form-check-input me-1 foodplan_checked-green" type="checkbox" value="" name="allergy3">
                                    <label class="form-check-label" for="allergy3">
                                        Продукты пчеловодства
                                    </label>
                                </div>
                                <div class="form-check d-flex justify-content-start">
                                    <input class="form-check-input me-1 foodplan_checked-green" type="checkbox" value="" name="allergy3">
                                    <label class="form-check-label" for="allergy3">
                                        Орехи и бобовые
                                    </label>
                                </div>
                                <div class="form-check d-flex justify-content-start">
                                    <input class="form-check-input me-1 foodplan_checked-green" type="checkbox" value="" name="allergy3">
                                    <label class="form-check-label" for="allergy3">
                                        Молочные продукты
                                    </label>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <button type="submit" id="TableSubmit" class="d-none"></button>
                </form>

                <form class="card d-flex flex-row align-items-baseline mb-5 p-3 foodplan__bg_grey">
                    <label for="exampleInputPassword1" class="form-label me-2">Промокод</label>
                    <input type="password" class="form-control me-2" id="password">
                    <button type="submit" class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">Применить</button>
                </form>
                <div class="d-flex justify-content-center my-5">
                    <button form="order" type="submit" class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green w-50">Оплатить</button>
                </div>
            </div>
        </section>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>