foodplan/urls.py
import os

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from foodplan import settings
from foodplan_site.views import index, free_menus, card

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('free_menus/', free_menus, name='free_menus'),
    path('card/', card, name='card'),
    path('users/', include('users.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import login, registration, profile, logout, order

app_name = 'users'

urlpatterns = [
    path('auth/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('lk/', profile, name='profile'),
    path('logout/', logout, name='logout'),
    path('order/', order, name='order'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_image', null=True, blank=True)

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control'
    }), required=False)
    image = forms.ImageField(widget=forms.FileInput(attrs={
        'class': 'form-control'
    }), required=False)

    class Meta:
        model = User
        fields = ('username', 'email',  'image')

users/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.contrib import auth
from django.urls import reverse
from django.utils.http import urlencode
from foodplan_site import functions
import foodplan_site
from foodplan_site.functions import menu, make_order_dict
from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from users.models import User
from foodplan_site.models import Order, Promo
from yookassa import Configuration, Payment
from environs import Env
import uuid

order_data = {}
print('9999999999', order_data)
env = Env()
env.read_env()
ACCOUNT_ID = env('YOUKASSA_ACCOUNT_ID')
U_KEY = env('U_KEY')


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('users:profile'))

    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'users/auth.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/registration.html', context)


def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
        else:
            print(form.errors)
    else:
        form = UserProfileForm(instance=request.user)
    orders = menu(request.user.id)
    context = {
        'form': form,
        'orders': orders,
        'path': request.path
    }
    return render(request, 'users/lk.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


def order(request):
    global order_data
    user = User.objects.get(username=request.user)
    if request.GET:
        order_id = request.GET.get('?!@', None)
        if order_id:
            order = Order.objects.get(id=order_id)
            order.paid = True
            order.save()
            cost = '0000'
            return render(request, 'users/order.html', context={'cost': cost, 'dic': order_data})
        pay = request.GET.get('pay', None)
        if not pay:
            order_data = make_order_dict(request)
            cost = functions.cost(order_data)
            return render(request, 'users/order.html', context={'cost': cost, 'dic': order_data})
        else:
            if not order_data:
                order_data = make_order_dict(request)
            order = Order.objects.create(
                user=user,
                breakfast=order_data['breakfast'],
                dinner=order_data['dinner'],
                supper=order_data['supper'],
                dessert=order_data['dessert'],
                person=order_data['person'],
                period=order_data['period'],
                classic=order_data['classic'],
                lowcarb=order_data['lowcarb'],
                vegan=order_data['vegan'],
                keto=order_data['keto'],
                allergic=order_data['allergic'],
                discount=order_data['discount']
            )
            order.save()
            cost = functions.cost(order_data)
            order_data = {}
            redirect_url = 'http://127.0.0.1:8000/users/order/' + '?' + urlencode({'?!@': order.id})
            Configuration.account_id = ACCOUNT_ID
            Configuration.secret_key = U_KEY
            payment = Payment.create({
                "amount": {
                    "value": f"{cost}",
                    "currency": "RUB"
                },
                "confirmation": {
                    "type": "redirect",
                    "return_url": redirect_url
                },
                "capture": True,
                "description": f"{order}",
                "metadata": {"order": order.id}
            }, uuid.uuid4())
            confirmation_url = payment.confirmation.confirmation_url
            return redirect(confirmation_url)
    else:
        context = {
            'cost': '0000',
            'dic': order_data
        }
    return render(request, 'users/order.html', context=context)

templates/users/auth.html
{% extends 'users/base.html' %}

{% block content %}
    <main style="margin-top: calc(2rem + 85px);">
        <section>
            <div class="container">
                <div class="card p-3 mb-5 foodplan__shadow">
                    <a href="#" class="link-secondary fw-light foodplan__backButton">
                        <svg xmlns="http://www.w3.org/2000/svg" width="9%" height="9%" fill="currentColor" class="bi bi-arrow-left-circle"
                            viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                        </svg>
                    </a>
                    <h2 class="text-center"><strong>Авторизация</strong></h2>
                </div>
                <div class="card px-5 py-3 d-flex align-items-center foodplan__shadow">
                    <form action="{% url 'users:login' %}" method="post">
                        {% csrf_token %}
                        <h1 class="mb-4 text-center"><strong>Вход</strong></h1>
                        <div class="mb-3">
                            <label for="{{ form.username.id_for_label }}" class="form-label">Логин</label>
                            {{ form.username }}
                        </div>
                        <div class="mb-3">
                            <div class="d-flex align-items-center justify-content-between">
                                <label for="{{ form.password.id_for_label }}" class="form-label">Пароль</label>
                                <small><a href="#" class="link-dark foodplan_green">Забыли пароль?</a></small>
                            </div>
                            {{ form.password }}
                        </div>
                        <div class="row mb-3">
                            <div class="col-12 col-sm-6 mt-3">
                                <button type="submit"
                                    class="btn w-100 btn-outline-success shadow-none foodplan_green foodplan__border_green">Войти</button>
                            </div>
                            <div class="col-12 col-sm-6 mt-3 d-flex justify-content-center align-items-center">
                                <small>Нет аккаунта? <a href="{% url 'users:registration' %}" class="link-dark foodplan_green">Зарегистрируйтесь</a></small>
                            </div>
                        </div>
                    </form>
                    {% if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                        style="margin-top: 50px;">
                        {{ form.errors }}
                        </div>
                    {% endif %}
                </div>
            </div>
        </section>
    </main>
{% endblock %}

templates/users/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Foodplan 2021 - Меню на неделю FOODPLAN</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light fixed-top navbar__opacity">
            <div class="container">
                <a class="navbar-brand" href="{% url 'index' %}">
                    <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse1"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse1">
                    <ul class="navbar-nav w-100">
                        {% if user.is_authenticated %}

                            <li class="nav-item align-items-center d-md-flex flex-grow-1 justify-content-end">
                                <button class="btn btn-outline-success me-2 shadow-none foodplan_green foodplan__border_green"
                                onclick="window.location.href='{% url 'users:profile' %}'">Личный кабинет</button>
                                <button class="btn btn-outline-success me-2 shadow-none foodplan_green foodplan__border_green"
                                onclick="window.location.href='{% url 'users:order' %}'">Подписка</button>
                                <button class="btn btn-outline-success shadow-none foodplan_green foodplan__border_green"
                                onclick="window.location.href='{% url 'users:logout' %}'">Выйти</button>
                            </li>
                        {% else %}
                            <li class="nav-item align-items-center d-md-flex flex-grow-1 justify-content-end">
                                <button class="btn btn-outline-success shadow-none foodplan_green foodplan__border_green"
                                onclick="window.location.href='{% url 'users:login' %}'">Войти</button>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
        {% block content %}{% endblock %}
{% include "footer.html" %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/users/lk.html
{% extends 'users/base.html' %}

{% block content %}
{% load static %}
    <main style="margin-top: calc(2rem + 85px);">
        <section>
            <div class="container">
                <div class="row">
                    <div class="card col-12 p-3 mb-5 foodplan__shadow">
                        <h4 class="foodplan__backButton">
                            <strong><small><a href="#" class="link-secondary fw-light"></a></small></strong>
                        </h4>
                        <h2 class="text-center"><strong>Личный кабинет</strong></h2>
                    </div>
                    
                    <div class="card col-12 col-md-2 p-3 mb-3 d-flex flex-column align-items-center foodplan__shadow">
                        <div class="position-relative">
                            <img src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'img/test_avatar.png' %} {% endif %}" alt="" width="100" height="100" class="rounded-pill">
                        </div>
                        <h3 class="card-title text-center">"{{ user.username }}"</h3>
                        <div class="d-block">
                            <button class="btn btn-outline-success shadow-none foodplan_green foodplan__border_green"
                            onclick="window.location.href='{% url 'users:logout' %}'">Выйти</button>
                        </div>
                    </div>

                    <div class="card col-12 col-md-10 p-3 mb-3 foodplan__shadow">
                            <ul class="nav nav-tabs">
                                <li class="nav-item foodplan__tab-item">
                                    <button id="tab1" class="btn shadow-none foodplan__tab-button active" data-bs-toggle="tab" data-bs-target="#data">Персональные данные</button>
                                </li>
                                <li class="nav-item foodplan__tab-item">
                                    <button id="tab2" class="btn shadow-none foodplan__tab-button" data-bs-toggle="tab" data-bs-target="#menu">Моё меню</button>
                                </li>
                                <li class="nav-item foodplan__tab-item flex-grow-1"></li>
                            </ul>
                            <div class="tab-content mt-2">
                                <div class="tab-pane fade show active" id="data">
                                    <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="mb-3">
                                            <div class="d-flex align-items-center justify-content-between">
                                                <label for="{{ form.username.id_for_label }}" class="form-label">Логин</label>
                                            </div>
                                        
                                            {{ form.username }}
                                        </div>
                                        <div class="mb-3">
                                            <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
                                            {{ form.email }}
                                        </div>
                                        <div class="mb-3">
                                            <label for="{{ form.image.id_for_label}}" class="custom-file">Фото</label>
                                            {{ form.image }}
                                        </div>
                                        <div class="d-block">
                                            <button type="submit" class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">Сохранить
                                                изменения</button>
                                        </div>
                                    </form>
                                    {% if form.errors %}
                                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                                        style="margin-top: 50px;">
                                        {{ form.errors }}
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="tab-pane fade" id="menu">
                                    <div class="row">
<!--                                        <div class="col-2">-->
<!--                                            <img src="{% static 'img/circle1.png'%}" alt="" class="w-100">-->
<!--                                        </div>-->
                                        <div class="col-10 col-md-10">
                                            <div class="row">
                                                <div class="col-12">
                                                    {% for order in orders %}

                                                    <h2>{{order}}</h2>
                                                </div>
                                                <div class="col-md-12 col-lg-9">

                                                    {% for i in order.days %}

                                                    <h6>
                                                        <h5>День {{i.num}}: <br></h5>
                                                        {% if i.breakfast %}
                                                        {% if i.breakfast == "время голодать" %}
                                                            <p>Завтрака нет: {{i.breakfast}}</p>
                                                        {% else %}
                                                            <p><a href="{% url 'card' %}?receipt_id={{i.breakfast.id}}&next={{path}}">Завтрак: {{i.breakfast.name}}</a></p>
                                                            <div class="col-2">
                                                                <img src="{% if i.breakfast.image %} {{ i.breakfast.image.url }} {% else %} {% static 'img/circle1.png' %} {% endif %}"
                                                                     alt="" class="w-100">
                                                            </div>
                                                        {% endif %}
                                                        {% endif %}
                                                        {% if i.dinner %}
                                                        {% if i.dinner == "время голодать" %}
                                                            <p>Обеда нет: {{i.dinner}}</p>
                                                        {% else %}
                                                            <p><a href="{% url 'card' %}?receipt_id={{i.dinner.id}}&next={{path}}">Обед: {{i.dinner.name}}</a></p>
                                                            <div class="col-2">
                                                                <img src="{% if i.dinner.image %} {{ i.dinner.image.url }} {% else %} {% static 'img/circle1.png' %} {% endif %}"
                                                                    alt="" class="w-100">
                                                            </div>


                                                        {% endif %}
                                                        {% endif %}
                                                        {% if i.supper %}
                                                        {% if i.supper == "время голодать" %}
                                                            <p>Ужина нет: {{i.supper}}</p>
                                                        {% else %}
                                                            <p><a href="{% url 'card' %}?receipt_id={{i.supper.id}}&next={{path}}">Ужин: {{i.supper.name}}</a></p>
                                                            <div class="col-2">
                                                                <img src="{% if i.supper.image %} {{ i.supper.image.url }} {% else %} {% static 'img/circle1.png' %} {% endif %}"
                                                                     alt="" class="w-100">
                                                            </div>
                                                        {% endif %}
                                                        {% endif %}
                                                        {% if i.dessert %}
                                                        {% if i.dessert == "время голодать" %}
                                                            <p>Десерта нет: {{i.dessert}}</p>
                                                        {% else %}
                                                            <p><a href="{% url 'card' %}?receipt_id={{i.dessert.id}}&next={{path}}">Десерт: {{i.dessert.name}}</a></p>
                                                            <div class="col-2">
                                                                <img src="{% if i.dessert.image %} {{ i.dessert.image.url }} {% else %} {% static 'img/circle1.png' %} {% endif %}"
                                                                     alt="" class="w-100">
                                                            </div>
                                                        {% endif %}
                                                        {% endif %}
                                                    </h6>
                                                    {% endfor %}
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}

templates/users/registration.html
{% extends 'users/base.html' %}

{% block content %}
    <main style="margin-top: calc(2rem + 85px);">
        <section>
            <div class="container">
                <div class="card p-3 mb-5 foodplan__shadow">
                    <a href="#" class="link-secondary fw-light foodplan__backButton">
                        <svg xmlns="http://www.w3.org/2000/svg" width="9%" height="9%" fill="currentColor" class="bi bi-arrow-left-circle"
                            viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                        </svg>
                    </a>
                    <h2 class="text-center"><strong>Авторизация</strong></h2>
                </div>
                <div class="card px-5 py-3 d-flex align-items-center foodplan__shadow">
                    <form action="{% url 'users:registration' %}" method="post">
                        {% csrf_token %}

                        <h1 class="mb-4 text-center"><strong>Регистрация</strong></h1>
                        <div class="mb-3">
                            <label for="{{ form.username.id_for_label }}" class="form-label">Логин</label>
                            {{ form.username }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
                            {{ form.email }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.password1.id_for_label }}" class="form-label">Пароль</label>
                            {{ form.password1 }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.password2.id_for_label }}" class="form-label">Подтверждение пароля</label>
                            {{ form.password2 }}
                        </div>
                        <div class="row mb-3">
                            <div class="col-12 col-sm-6 mt-3">
                                <button type="submit" class="btn  shadow-nonew-100 btn-outline-success foodplan_green foodplan__border_green">Регистрация</button>
                            </div>
                            <div class="col-12 col-sm-6 mt-3 d-flex justify-content-center align-items-center">
                                <small>Уже есть аккаунт? <a href="{% url 'users:login' %}" class="link-dark foodplan_green">Войти</a></small>
                            </div>
                        </div>
                    </form>
                    {% if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                        style="margin-top: 50px;">
                        {{ form.errors }}
                        </div>
                    {% endif %}
                </div>

            </div>
        </section>
    </main>
{% endblock %}